# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='início')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('slots', models.IntegerField(verbose_name='capacidade')),
                ('speakers', models.ManyToManyField(blank=True, to='core.Speaker', verbose_name='Palestrantes')),
            ],
            options={
                'verbose_name_plural': 'cursos',
                'verbose_name': 'curso',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='speakers',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
